// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD75BxF27AylA5ovW0P31tRhNmVDqkPdmo',
    appId: '1:246909659099:web:d895cd499e83672b9429fe',
    messagingSenderId: '246909659099',
    projectId: 'davai-store-6efa1',
    authDomain: 'davai-store-6efa1.firebaseapp.com',
    storageBucket: 'davai-store-6efa1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1bsS_1LFTqdoZBNjZZO8GWfyMjd_-NPk',
    appId: '1:246909659099:android:fda7456edb45e13f9429fe',
    messagingSenderId: '246909659099',
    projectId: 'davai-store-6efa1',
    storageBucket: 'davai-store-6efa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZxGykph4HLfes7beFsBOiN2eD7eW0cvU',
    appId: '1:246909659099:ios:aff09f71c402628d9429fe',
    messagingSenderId: '246909659099',
    projectId: 'davai-store-6efa1',
    storageBucket: 'davai-store-6efa1.firebasestorage.app',
    iosBundleId: 'com.example.davaistoreMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZxGykph4HLfes7beFsBOiN2eD7eW0cvU',
    appId: '1:246909659099:ios:aff09f71c402628d9429fe',
    messagingSenderId: '246909659099',
    projectId: 'davai-store-6efa1',
    storageBucket: 'davai-store-6efa1.firebasestorage.app',
    iosBundleId: 'com.example.davaistoreMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD75BxF27AylA5ovW0P31tRhNmVDqkPdmo',
    appId: '1:246909659099:web:1bfb5f4e173308e39429fe',
    messagingSenderId: '246909659099',
    projectId: 'davai-store-6efa1',
    authDomain: 'davai-store-6efa1.firebaseapp.com',
    storageBucket: 'davai-store-6efa1.firebasestorage.app',
  );
}
